name = "kawal-spip"
compatibility_date = "2026-09-11"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kawal-spip-db"
database_id = "GANTI_DENGAN_UUID_D1_LENGKAP"

[[r2_buckets]]
binding = "EVIDENCE_BUCKET"
bucket_name = "kawal-spip-files"

[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeHub"
script_name = "kawal-spip-realtime"
