name = "kawal-spip-realtime"
main = "realtime.js"
compatibility_date = "2026-09-10"

[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeHub"

[exports.RealtimeHub]
type = "durable-object"
storage = "sqlite"
